/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SquadsIndexRouteImport } from './routes/squads/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms/index'
import { Route as SquadsCodeRouteImport } from './routes/squads/$code'
import { Route as RoomsMyRouteImport } from './routes/rooms/my'
import { Route as RoomsCodeRouteImport } from './routes/rooms/$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadsIndexRoute = SquadsIndexRouteImport.update({
  id: '/squads/',
  path: '/squads/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadsCodeRoute = SquadsCodeRouteImport.update({
  id: '/squads/$code',
  path: '/squads/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsMyRoute = RoomsMyRouteImport.update({
  id: '/rooms/my',
  path: '/rooms/my',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsCodeRoute = RoomsCodeRouteImport.update({
  id: '/rooms/$code',
  path: '/rooms/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rooms/$code': typeof RoomsCodeRoute
  '/rooms/my': typeof RoomsMyRoute
  '/squads/$code': typeof SquadsCodeRoute
  '/rooms/': typeof RoomsIndexRoute
  '/squads/': typeof SquadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rooms/$code': typeof RoomsCodeRoute
  '/rooms/my': typeof RoomsMyRoute
  '/squads/$code': typeof SquadsCodeRoute
  '/rooms': typeof RoomsIndexRoute
  '/squads': typeof SquadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rooms/$code': typeof RoomsCodeRoute
  '/rooms/my': typeof RoomsMyRoute
  '/squads/$code': typeof SquadsCodeRoute
  '/rooms/': typeof RoomsIndexRoute
  '/squads/': typeof SquadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rooms/$code'
    | '/rooms/my'
    | '/squads/$code'
    | '/rooms/'
    | '/squads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rooms/$code'
    | '/rooms/my'
    | '/squads/$code'
    | '/rooms'
    | '/squads'
  id:
    | '__root__'
    | '/'
    | '/rooms/$code'
    | '/rooms/my'
    | '/squads/$code'
    | '/rooms/'
    | '/squads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomsCodeRoute: typeof RoomsCodeRoute
  RoomsMyRoute: typeof RoomsMyRoute
  SquadsCodeRoute: typeof SquadsCodeRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
  SquadsIndexRoute: typeof SquadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squads/': {
      id: '/squads/'
      path: '/squads'
      fullPath: '/squads/'
      preLoaderRoute: typeof SquadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squads/$code': {
      id: '/squads/$code'
      path: '/squads/$code'
      fullPath: '/squads/$code'
      preLoaderRoute: typeof SquadsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/my': {
      id: '/rooms/my'
      path: '/rooms/my'
      fullPath: '/rooms/my'
      preLoaderRoute: typeof RoomsMyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$code': {
      id: '/rooms/$code'
      path: '/rooms/$code'
      fullPath: '/rooms/$code'
      preLoaderRoute: typeof RoomsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomsCodeRoute: RoomsCodeRoute,
  RoomsMyRoute: RoomsMyRoute,
  SquadsCodeRoute: SquadsCodeRoute,
  RoomsIndexRoute: RoomsIndexRoute,
  SquadsIndexRoute: SquadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
